"""Server-side Mermaid code block post-processor.

Validates and optionally repairs Mermaid diagrams generated by LLMs
*before* they reach the frontend renderer.  Runs on the final assembled
response text — not on individual stream chunks (Mermaid blocks span
multiple lines so chunk-level processing is impractical).

Usage::

    from app.services.mermaid_validator import post_process_mermaid_blocks
    fixed_text = post_process_mermaid_blocks(llm_response_text)
"""

from __future__ import annotations

import logging
import re

logger = logging.getLogger("agenthub.mermaid_validator")

# ── Patterns ──────────────────────────────────────────────────────────────

# Match ```mermaid ... ``` code blocks (case-insensitive, optional language suffix)
MERMAID_BLOCK_RE = re.compile(
    r'```mermaid\s*\n(.*?)```',
    re.DOTALL | re.IGNORECASE,
)

# Invisible / zero-width Unicode characters LLMs sometimes inject
INVISIBLE_CHARS_RE = re.compile(
    r'[​‌‍‎‏﻿ ⁠⁡⁢⁣⁤'
    r'  ‪‫‬‭‮⁦⁧⁨⁩]'
)

# Deprecated ``graph`` keyword — should be ``flowchart`` in Mermaid >=10.x
GRAPH_RE = re.compile(r'^(graph\s+(TB|TD|BT|RL|LR))', re.MULTILINE)

# Node ID pattern: letters, digits, underscores only
VALID_NODE_ID_RE = re.compile(r'^[A-Za-z0-9_]+$')


def post_process_mermaid_blocks(text: str) -> str:
    """Find and repair all Mermaid code blocks in *text*.

    Returns the repaired text (or original if no blocks found / nothing
    to fix).  This is intended to run on the final synthesized LLM
    response before it is saved to history or streamed to the frontend.
    """
    if '```mermaid' not in text:
        return text

    def _repair_block(match: re.Match[str]) -> str:
        code = match.group(1)
        repaired = _repair_single(code)
        return f'```mermaid\n{repaired}```'

    try:
        return MERMAID_BLOCK_RE.sub(_repair_block, text)
    except Exception:
        logger.debug("mermaid_validator: post-processing failed", exc_info=True)
        return text


def _repair_single(code: str) -> str:
    """Apply all repair passes to a single Mermaid code block."""
    if not code or not code.strip():
        return code

    c = code

    # Pass 1: Strip invisible characters
    c = INVISIBLE_CHARS_RE.sub('', c)

    # Pass 2: Normalize line endings
    c = c.replace('\r\n', '\n').replace('\r', '\n')

    # Pass 3: Replace deprecated ``graph`` with ``flowchart``
    c = GRAPH_RE.sub(r'flowchart \2', c)

    # Pass 4: Strip markdown artifact lines
    c = re.sub(r'^```[\s\w]*$', '', c, flags=re.MULTILINE)

    # Pass 5: Line-by-line fixes
    lines = c.split('\n')
    fixed: list[str] = []
    subgraph_depth = 0

    for line in lines:
        if not line.strip():
            fixed.append(line)
            continue

        # Track subgraph balance
        stripped_lower = line.strip().lower()
        if re.match(r'^subgraph\s', stripped_lower):
            subgraph_depth += 1
        elif stripped_lower == 'end' and subgraph_depth > 0:
            subgraph_depth -= 1

        # Strip LLM-added line-number prefixes ("1. ", "2) ")
        line = re.sub(
            r'^(\s*)\d{1,3}[\.\)、．]\s+(?=[A-Za-z_][A-Za-z0-9_]*\s*[\[\(\{])',
            r'\1',
            line,
        )

        # Fix subgraph names with spaces/special chars
        line = re.sub(
            r'^(\s*subgraph\s+)([^"\'\n].*)$',
            lambda m: (
                m.group(1) + f'"{m.group(2).strip()}"'
                if re.search(r'[\s一-鿿]', m.group(2))
                else m.group(0)
            ),
            line,
            flags=re.IGNORECASE,
        )

        # Fix bare & that aren't HTML entities
        line = re.sub(r'&(?!amp;|lt;|gt;|quot;|#39;|#\d+;|#x[0-9a-fA-F]+;)', '&amp;', line)

        fixed.append(line)

    # Close unclosed subgraphs
    while subgraph_depth > 0:
        fixed.append('end')
        subgraph_depth -= 1

    # Trim leading/trailing empty lines
    while fixed and not fixed[0].strip():
        fixed.pop(0)
    while fixed and not fixed[-1].strip():
        fixed.pop()

    return '\n'.join(fixed)


def validate_mermaid_block(code: str) -> str | None:
    """Quick validation of a Mermaid code block.

    Returns ``None`` if the code looks OK, or an error message string
    describing the problem.
    """
    if not code or not code.strip():
        return 'Mermaid 代码块为空'

    first_line = code.strip().split('\n')[0].strip()
    first_word = first_line.split()[0] if first_line else ''

    valid_starters = {
        'flowchart', 'graph', 'sequencediagram', 'classdiagram',
        'statediagram', 'erdiagram', 'journey', 'gantt', 'pie',
        'gitgraph', 'mindmap', 'timeline', 'sankey', 'block',
        'quadrantchart', 'xychart', 'requirementdiagram',
        'c4context', 'c4container', 'c4component',
    }

    if first_word.lower() not in valid_starters:
        return f'未知的图表类型: "{first_word}"，期望以 flowchart/sequenceDiagram 等开头'

    if '```' in code:
        return '代码中包含 Markdown 代码块标记 ```，请移除'

    return None  # OK
