"""Unit tests for `agenthub review-pr` (I-4).

The review adapter reuses the verifier-gated mission loop: the CLI
stages the diff plus a CLI-written validator (independent of the
executing agent), the agent produces review-findings.json, and the
exit-code contract maps blocking findings to exit 1.
"""

from __future__ import annotations

import json
import subprocess
import sys
import unittest
from pathlib import Path
from unittest import mock

from app.cli import review
from app.cli.main import build_parser
from app.cli.runtime import MissionRunResult

SAMPLE_DIFF = """\
diff --git a/app/widget.py b/app/widget.py
index 1111111..2222222 100644
--- a/app/widget.py
+++ b/app/widget.py
@@ -10,6 +10,7 @@ def render(name):
-    return f"<p>{name}</p>"
+    return f"<p>{html.escape(name)}</p>"
"""


def _result(exit_code: int, status: str = "SUCCEEDED") -> MissionRunResult:
    return MissionRunResult(
        mission_id="m-test",
        status=status,
        objective="review",
        work_unit_statuses=[],
        artifacts=[],
        workspace_files=[],
        wall_seconds=1.0,
        waited_timeout=False,
        exit_code=exit_code,
    )


class StageWorkspaceTests(unittest.TestCase):
    def setUp(self) -> None:
        import tempfile

        self.tmp = tempfile.TemporaryDirectory()
        self.workspace = Path(self.tmp.name)

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def test_stages_diff_and_cli_written_validator(self) -> None:
        review.stage_review_workspace(self.workspace, SAMPLE_DIFF)
        self.assertEqual(
            (self.workspace / "pr.diff").read_text(encoding="utf-8"),
            SAMPLE_DIFF,
        )
        validator = self.workspace / "_agenthub_review_validate.py"
        self.assertTrue(validator.is_file())
        # The validator source is authored by the CLI (part of the repo,
        # never generated by the agent under review).
        self.assertIn("review-findings.json", validator.read_text(encoding="utf-8"))

    def test_objective_names_validator_as_verify_gate(self) -> None:
        objective = review.build_review_objective()
        self.assertIn("VERIFY: python _agenthub_review_validate.py", objective)
        self.assertIn("pr.diff", objective)
        self.assertIn("blocking", objective)


class ReviewExitCodeTests(unittest.TestCase):
    def test_clean_findings_pass(self) -> None:
        findings = {"blocking": [], "warnings": [{"file": "a.py"}], "nits": []}
        self.assertEqual(review.review_exit_code(_result(0), findings), 0)

    def test_blocking_findings_fail(self) -> None:
        findings = {"blocking": [{"file": "a.py", "issue": "bug", "suggestion": "fix"}]}
        self.assertEqual(review.review_exit_code(_result(0), findings), 1)

    def test_mission_failure_propagates(self) -> None:
        self.assertEqual(review.review_exit_code(_result(1, "FAILED"), None), 1)

    def test_success_without_findings_is_infra_error(self) -> None:
        # Mission claimed success but no readable findings document —
        # a breach of the review contract, not a pass.
        self.assertEqual(review.review_exit_code(_result(0), None), 4)

    def test_missing_findings_file_loads_none(self) -> None:
        self.assertIsNone(review.load_findings(Path("no-such-dir")))
        self.assertEqual(
            review.review_exit_code(_result(0), review.load_findings(Path("no-such-dir"))),
            4,
        )


class ValidatorExecutionTests(unittest.TestCase):
    """Run the staged validator for real — it is the verifier."""

    def setUp(self) -> None:
        import tempfile

        self.tmp = tempfile.TemporaryDirectory()
        self.workspace = Path(self.tmp.name)
        review.stage_review_workspace(self.workspace, SAMPLE_DIFF)

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def _run_validator(self) -> subprocess.CompletedProcess:
        return subprocess.run(
            [sys.executable, "_agenthub_review_validate.py"],
            cwd=self.workspace,
            capture_output=True,
            text=True,
        )

    def test_valid_clean_findings_pass(self) -> None:
        (self.workspace / "review-findings.json").write_text(
            json.dumps({"blocking": [], "warnings": [], "nits": []}),
            encoding="utf-8",
        )
        proc = self._run_validator()
        self.assertEqual(proc.returncode, 0, proc.stderr)

    def test_blocking_finding_on_real_file_passes_validation(self) -> None:
        (self.workspace / "review-findings.json").write_text(
            json.dumps(
                {
                    "blocking": [
                        {
                            "file": "app/widget.py",
                            "category": "correctness",
                            "issue": "x",
                            "suggestion": "y",
                        }
                    ],
                    "warnings": [],
                    "nits": [],
                }
            ),
            encoding="utf-8",
        )
        proc = self._run_validator()
        self.assertEqual(proc.returncode, 0, proc.stderr)

    def test_finding_on_file_not_in_diff_rejected(self) -> None:
        # An agent cannot review files the PR does not touch.
        (self.workspace / "review-findings.json").write_text(
            json.dumps(
                {
                    "blocking": [
                        {
                            "file": "not/in/the-diff.py",
                            "category": "correctness",
                            "issue": "x",
                            "suggestion": "y",
                        }
                    ],
                    "warnings": [],
                    "nits": [],
                }
            ),
            encoding="utf-8",
        )
        proc = self._run_validator()
        self.assertEqual(proc.returncode, 1)

    def test_missing_key_rejected(self) -> None:
        (self.workspace / "review-findings.json").write_text(
            json.dumps({"blocking": []}), encoding="utf-8"
        )
        proc = self._run_validator()
        self.assertEqual(proc.returncode, 1)

    def test_bad_category_rejected(self) -> None:
        (self.workspace / "review-findings.json").write_text(
            json.dumps(
                {
                    "blocking": [
                        {
                            "file": "app/widget.py",
                            "category": "not-a-category",
                            "issue": "x",
                            "suggestion": "y",
                        }
                    ],
                    "warnings": [],
                    "nits": [],
                }
            ),
            encoding="utf-8",
        )
        proc = self._run_validator()
        self.assertEqual(proc.returncode, 1)

    def test_no_findings_file_rejected(self) -> None:
        proc = self._run_validator()
        self.assertEqual(proc.returncode, 1)


class ParserTests(unittest.TestCase):
    def test_review_pr_subcommand_parses(self) -> None:
        args = build_parser().parse_args(
            ["review-pr", "--diff-file", "pr.diff", "--json"]
        )
        self.assertEqual(args.command, "review-pr")
        self.assertEqual(args.diff_file, "pr.diff")
        self.assertTrue(args.json)
        self.assertFalse(args.no_web_search)


class CmdReviewPrTests(unittest.TestCase):
    def _args(self, diff_file: str | None):
        argv = ["review-pr"]
        if diff_file:
            argv += ["--diff-file", diff_file]
        argv += ["--json"]
        return build_parser().parse_args(argv)

    def test_missing_diff_returns_infra_error(self) -> None:
        from app.cli.main import cmd_review_pr

        with mock.patch.dict("os.environ", {}, clear=True):
            code = cmd_review_pr(self._args(None), Path("."))
        self.assertEqual(code, 4)

    def test_unreadable_diff_returns_infra_error(self) -> None:
        from app.cli.main import cmd_review_pr

        code = cmd_review_pr(self._args("Z:/no/such/file.diff"), Path("."))
        self.assertEqual(code, 4)

    def test_empty_diff_skips_cleanly(self) -> None:
        import tempfile

        from app.cli.main import cmd_review_pr

        with tempfile.TemporaryDirectory() as tmp:
            empty = Path(tmp) / "empty.diff"
            empty.write_text("", encoding="utf-8")
            code = cmd_review_pr(self._args(str(empty)), Path(tmp))
        self.assertEqual(code, 0)


if __name__ == "__main__":
    unittest.main()
