module.exports = {
  content: ['./pages/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}', './styles/**/*.css'],
  theme: {
    extend: {
      colors: {
        warm: {
          50:  'rgb(var(--warm-50)  / <alpha-value>)',
          100: 'rgb(var(--warm-100) / <alpha-value>)',
          150: 'rgb(var(--warm-150) / <alpha-value>)',
          200: 'rgb(var(--warm-200) / <alpha-value>)',
          300: 'rgb(var(--warm-300) / <alpha-value>)',
          400: 'rgb(var(--warm-400) / <alpha-value>)',
          500: 'rgb(var(--warm-500) / <alpha-value>)',
          600: 'rgb(var(--warm-600) / <alpha-value>)',
          700: 'rgb(var(--warm-700) / <alpha-value>)',
          800: 'rgb(var(--warm-800) / <alpha-value>)',
          900: 'rgb(var(--warm-900) / <alpha-value>)',
        },
        sidebar: {
          DEFAULT: '#151412',
          bg: '#151412',
        },
        primary: {
          50:  'rgb(var(--primary-50)  / <alpha-value>)',
          100: 'rgb(var(--primary-100) / <alpha-value>)',
          200: 'rgb(var(--primary-200) / <alpha-value>)',
          300: 'rgb(var(--primary-300) / <alpha-value>)',
          400: 'rgb(var(--primary-400) / <alpha-value>)',
          500: 'rgb(var(--primary-500) / <alpha-value>)',
          600: 'rgb(var(--primary-600) / <alpha-value>)',
          700: 'rgb(var(--primary-700) / <alpha-value>)',
        },
        accent: {
          50:  'rgb(var(--accent-50)  / <alpha-value>)',
          100: 'rgb(var(--accent-100) / <alpha-value>)',
          200: 'rgb(var(--accent-200) / <alpha-value>)',
          300: 'rgb(var(--accent-300) / <alpha-value>)',
          400: 'rgb(var(--accent-400) / <alpha-value>)',
          500: 'rgb(var(--accent-500) / <alpha-value>)',
          600: 'rgb(var(--accent-600) / <alpha-value>)',
          700: 'rgb(var(--accent-700) / <alpha-value>)',
        },
        success: {
          50:  'rgb(var(--success-50)  / <alpha-value>)',
          100: 'rgb(var(--success-100) / <alpha-value>)',
          200: 'rgb(var(--success-200) / <alpha-value>)',
          500: 'rgb(var(--success-500) / <alpha-value>)',
          600: 'rgb(var(--success-600) / <alpha-value>)',
          700: 'rgb(var(--success-700) / <alpha-value>)',
        },
        warning: {
          50:  'rgb(var(--warning-50)  / <alpha-value>)',
          100: 'rgb(var(--warning-100) / <alpha-value>)',
          200: 'rgb(var(--warning-200) / <alpha-value>)',
          500: 'rgb(var(--warning-500) / <alpha-value>)',
          600: 'rgb(var(--warning-600) / <alpha-value>)',
          700: 'rgb(var(--warning-700) / <alpha-value>)',
        },
        danger: {
          50:  'rgb(var(--danger-50)  / <alpha-value>)',
          100: 'rgb(var(--danger-100) / <alpha-value>)',
          200: 'rgb(var(--danger-200) / <alpha-value>)',
          500: 'rgb(var(--danger-500) / <alpha-value>)',
          600: 'rgb(var(--danger-600) / <alpha-value>)',
          700: 'rgb(var(--danger-700) / <alpha-value>)',
        },
      },
      borderColor: {
        focus: '#3D3A34',
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '4px',
        md: '4px',
        lg: '4px',
        xl: '4px',
        '2xl': '4px',
        '3xl': '4px',
      },
      boxShadow: {
        'card': '0 1px 2px rgba(var(--shadow-color), calc(var(--shadow-strength) * 1))',
        'card-hover': '0 2px 4px rgba(var(--shadow-color), calc(var(--shadow-strength) * 1.5))',
        'card-elevated': '0 2px 4px rgba(var(--shadow-color), calc(var(--shadow-strength) * 1.5))',
        'modal': '0 4px 12px rgba(var(--shadow-color), calc(var(--shadow-strength) * 2))',
        'sidebar': '0 2px 8px rgba(var(--shadow-color), calc(var(--shadow-strength) * 2))',
        'button-primary': '0 1px 2px rgba(0, 0, 0, 0.2)',
        'button-accent': '0 1px 2px rgba(0, 0, 0, 0.2)',
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', '"Helvetica Neue"', 'Arial', '"Noto Sans SC"', 'sans-serif', '"Apple Color Emoji"', '"Segoe UI Emoji"'],
        mono: ['"JetBrains Mono"', '"Fira Code"', '"Cascadia Code"', '"IBM Plex Mono"', 'Consolas', '"SF Mono"', 'monospace'],
      },
      fontSize: {
        'h1': ['20px', { lineHeight: '1.3', fontWeight: '600' }],
        'h2': ['16px', { lineHeight: '1.4', fontWeight: '600' }],
        'h3': ['14px', { lineHeight: '1.4', fontWeight: '600' }],
        'h4': ['13px', { lineHeight: '1.5', fontWeight: '600' }],
        'body': ['13px', { lineHeight: '1.6' }],
        'caption': ['11px', { lineHeight: '1.5' }],
        'xs': ['10px', { lineHeight: '1.5' }],
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out',
        'fade-in-up': 'fadeInUp 0.25s ease-out',
        'shimmer': 'shimmer 1.5s ease-in-out infinite',
        'breathe': 'breathe 2s ease-in-out infinite',
        'spin-slow': 'spin 3s linear infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeInUp: { '0%': { opacity: '0', transform: 'translateY(8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        breathe: { '0%, 100%': { opacity: '0.6' }, '50%': { opacity: '1' } },
        spin: { '0%': { transform: 'rotate(0deg)' }, '100%': { transform: 'rotate(360deg)' } },
      },
    },
  },
  plugins: [],
};
