from __future__ import annotations

from typing import Any


class SubprocessProtocol:
    """Abstract protocol for subprocess-based CLI agents.

    Each CLI (Claude Code, Codex CLI, OpenClaw) has its own protocol
    subclass that knows how to:

    - Encode user messages for the CLI's stdin format
    - Encode tool results for feedback to the CLI
    - Report whether the CLI supports interactive (bidirectional) mode
    - Build the interactive-mode command line
    - Extract session identifiers for multi-turn continuity

    This is a **collaboration component** for :class:`CloudCodeAdapter`,
    not a replacement — the adapter owns the subprocess lifecycle; the
    protocol owns the message encoding/decoding strategy.
    """

    # Unique key matching an adapter_type in AdapterManager
    adapter_type: str = ""

    # ── Interactive mode ────────────────────────────────────────────

    def supports_interactive(self) -> bool:
        """Return ``True`` when the CLI supports bidirectional JSON Lines.

        When ``False``, callers should use the one-shot ``stream_prompt()``
        path — the subprocess writes the prompt to stdin, closes it, and
        reads until EOF.
        """
        return False

    def get_interactive_command(self) -> list[str]:
        """Return the command line for interactive (keep-alive) mode.

        Must be overridden by subclasses that return ``True`` from
        ``supports_interactive()``.
        """
        return []

    # ── Message encoding ────────────────────────────────────────────

    def encode_user_message(
        self,
        content: str,
        turn_id: str,
        attachments: list[dict[str, Any]] | None = None,
    ) -> str:
        """Encode a user message for the CLI's stdin.

        Returns a string (typically a JSON Line) ready to be written
        to the subprocess's stdin.

        Parameters
        ----------
        content:
            The user's message text (with attachment/quote context already
            merged by the caller).
        turn_id:
            Opaque turn identifier generated by AgentHub.
        attachments:
            Optional metadata about attached files (not used by all protocols).
        """
        return content  # default: raw text (one-shot mode)

    def encode_tool_result(
        self,
        tool_use_id: str,
        tool_name: str,
        result: dict[str, Any],
        is_error: bool = False,
    ) -> str:
        """Encode a tool execution result for feedback to the CLI.

        Returns a string (typically a JSON Line) ready to be written
        to the subprocess's stdin via ``send_input()``.
        """
        return ""

    # ── Session management ──────────────────────────────────────────

    def extract_session_id(self, raw: dict[str, Any]) -> str | None:
        """Extract the CLI's internal session/thread identifier from an event.

        For Claude Code, this is the ``session_id`` field in ``assistant``
        events.  The caller caches it for subsequent ``--resume`` calls.
        """
        return None
