"""Compatibility exports for immutable Mission control-plane migration history.

SQL definitions live in small domain modules. Revision identities and public
imports remain here so existing Alembic revisions and SQLite translation keep
the same migration graph and statement order.
"""

from app.db.migrations.mission_schema import (  # noqa: F401 - compatibility exports
    MISSION_CONTROL_PLANE_UPGRADE,
    MISSION_CONTROL_PLANE_DOWNGRADE,
    MISSION_EVENT_LEDGER_UPGRADE,
    MISSION_EVENT_LEDGER_DOWNGRADE,
)

from app.db.migrations.work_unit_schema import (  # noqa: F401 - compatibility exports
    WORK_UNIT_PERSISTENCE_UPGRADE,
    WORK_UNIT_PERSISTENCE_DOWNGRADE,
    A2A_SOURCE_MAPPING_UPGRADE,
    A2A_SOURCE_MAPPING_DOWNGRADE,
    DELEGATION_PERSISTENCE_UPGRADE,
    DELEGATION_PERSISTENCE_DOWNGRADE,
    AGENT_BINDING_PERSISTENCE_UPGRADE,
    AGENT_BINDING_PERSISTENCE_DOWNGRADE,
    AGENT_CATALOG_PROJECTION_UPGRADE,
    AGENT_CATALOG_PROJECTION_DOWNGRADE,
    A2A_INBOUND_SOURCE_MAPPING_UPGRADE,
    A2A_INBOUND_SOURCE_MAPPING_DOWNGRADE,
)

from app.db.migrations.artifact_schema import (  # noqa: F401 - compatibility exports
    MISSION_ARTIFACT_TABLE_UPGRADE,
    ARTIFACT_PERSISTENCE_UPGRADE,
    ARTIFACT_PERSISTENCE_DOWNGRADE,
    EVIDENCE_PROJECTION_UPGRADE,
    EVIDENCE_PROJECTION_DOWNGRADE,
    ARTIFACT_TABLE_OWNERSHIP_UPGRADE,
    ARTIFACT_TABLE_OWNERSHIP_DOWNGRADE,
)

from app.db.migrations.decision_schema import (  # noqa: F401 - compatibility exports
    DECISION_PERSISTENCE_UPGRADE,
    DECISION_PERSISTENCE_DOWNGRADE,
    DECISION_EXPIRY_UPGRADE,
    DECISION_EXPIRY_DOWNGRADE,
)

from app.db.migrations.contract_schema import (  # noqa: F401 - compatibility exports
    CONTRACT_REVISION_BINDING_UPGRADE,
    CONTRACT_REVISION_BINDING_DOWNGRADE,
    CONTRACT_LINEAGE_OWNERSHIP_UPGRADE,
    CONTRACT_LINEAGE_OWNERSHIP_DOWNGRADE,
)

from app.db.migrations.checkpoint_schema import (  # noqa: F401 - compatibility exports
    EXECUTION_CHECKPOINT_UPGRADE,
    EXECUTION_CHECKPOINT_DOWNGRADE,
)

from app.db.migrations.session_schema import (  # noqa: F401 - compatibility exports
    SESSION_EVENTS_UPGRADE,
    SESSION_EVENTS_DOWNGRADE,
    SESSIONS_UPGRADE,
    SESSIONS_DOWNGRADE,
    PENDING_CONFIRMATIONS_UPGRADE,
    PENDING_CONFIRMATIONS_DOWNGRADE,
)

MISSION_CONTROL_PLANE_REVISION = "4f6d2a8c901b"
MISSION_CONTROL_PLANE_DOWN_REVISION = "c1a7d4e82b6f"
MISSION_EVENT_LEDGER_REVISION = "8b7c3d9e0a12"
MISSION_EVENT_LEDGER_DOWN_REVISION = MISSION_CONTROL_PLANE_REVISION
WORK_UNIT_PERSISTENCE_REVISION = "9c8d4e0f1b23"
WORK_UNIT_PERSISTENCE_DOWN_REVISION = MISSION_EVENT_LEDGER_REVISION
A2A_SOURCE_MAPPING_REVISION = "a47e5f102c34"
A2A_SOURCE_MAPPING_DOWN_REVISION = WORK_UNIT_PERSISTENCE_REVISION
ARTIFACT_PERSISTENCE_REVISION = "b58f6a213d45"
ARTIFACT_PERSISTENCE_DOWN_REVISION = A2A_SOURCE_MAPPING_REVISION
EVIDENCE_PROJECTION_REVISION = "c69e7b324f56"
EVIDENCE_PROJECTION_DOWN_REVISION = ARTIFACT_PERSISTENCE_REVISION
DELEGATION_PERSISTENCE_REVISION = "d7a1b2c3e4f5"
DELEGATION_PERSISTENCE_DOWN_REVISION = EVIDENCE_PROJECTION_REVISION
AGENT_BINDING_PERSISTENCE_REVISION = "e8b2c3d4f5a6"
AGENT_BINDING_PERSISTENCE_DOWN_REVISION = DELEGATION_PERSISTENCE_REVISION
AGENT_CATALOG_PROJECTION_REVISION = "f9c3d4e5a6b7"
AGENT_CATALOG_PROJECTION_DOWN_REVISION = AGENT_BINDING_PERSISTENCE_REVISION
A2A_INBOUND_SOURCE_MAPPING_REVISION = "a0d4e5f6b7c8"
A2A_INBOUND_SOURCE_MAPPING_DOWN_REVISION = AGENT_CATALOG_PROJECTION_REVISION
DECISION_PERSISTENCE_REVISION = "b1e5f6a7c8d9"
DECISION_PERSISTENCE_DOWN_REVISION = A2A_INBOUND_SOURCE_MAPPING_REVISION
DECISION_EXPIRY_REVISION = "c2f6a7b8d9e0"
DECISION_EXPIRY_DOWN_REVISION = DECISION_PERSISTENCE_REVISION
ARTIFACT_TABLE_OWNERSHIP_REVISION = "d3a7b8c9e0f1"
ARTIFACT_TABLE_OWNERSHIP_DOWN_REVISION = DECISION_EXPIRY_REVISION
CONTRACT_REVISION_BINDING_REVISION = "e4b8c9d0f1a2"
CONTRACT_REVISION_BINDING_DOWN_REVISION = ARTIFACT_TABLE_OWNERSHIP_REVISION
CONTRACT_LINEAGE_OWNERSHIP_REVISION = "f5c9d0e1a2b3"
CONTRACT_LINEAGE_OWNERSHIP_DOWN_REVISION = CONTRACT_REVISION_BINDING_REVISION
EXECUTION_CHECKPOINT_REVISION = "a6d0e1f2b3c4"
EXECUTION_CHECKPOINT_DOWN_REVISION = CONTRACT_LINEAGE_OWNERSHIP_REVISION
