"""Compatibility shim — all real code lives in sibling modules.

Split history:
- web_search.py   — web_search_handler + providers
- file_ops.py     — file_read, file_write, file_write_batch, file_search,
                     file_patch, file_edit, file_glob, mkdir
- code_execute.py — code_execute_handler
- memory.py       — memory_save_handler, memory_search_handler

This file re-exports every public symbol for backward compatibility.
"""

from __future__ import annotations

from app.services.tools._common import (
    logging,
    os,
    subprocess,
    tempfile,
    Path,
    Any,
    MEMORY_DIR,
    sandbox_executor,
    aexists,
    aisfile,
    aisdir,
    aread_text,
    awrite_text,
    astat_size,
    aiterdir,
    amkdir,
    logger,
    MAX_FILE_READ_BYTES,
    MAX_FILE_LINES,
    CODE_EXECUTE_TIMEOUT,
    CODE_EXECUTE_INSTALL_TIMEOUT,
    MAX_CODE_OUTPUT_CHARS,
    _safe_path,
    _compute_unified_diff,
    _broadcast_workspace_change,
    _record_file_version,
    _auto_git_commit,
    _get_sid_fast,
    _get_uid_fast,
)

from app.services.tools.web_search import (
    logging,
    Any,
    logger,
    _VALID_SEARCH_MODES,
    _FREE_PROVIDERS,
    _resolve_search_providers,
    _apply_domain_filters,
    web_search_handler,
    _make_unavailable_output,
    _make_search_output,
    _search_bing,
    _search_tavily,
    _search_brave,
    _search_serpapi,
    _search_google_cse,
    _search_duckduckgo,
    normalize_hit,
)

from app.services.tools.file_ops import (
    logging,
    os,
    Path,
    Any,
    MAX_FILE_READ_BYTES,
    _auto_git_commit,
    _broadcast_workspace_change,
    _compute_unified_diff,
    _get_sid_fast,
    _get_uid_fast,
    aexists,
    aisfile,
    aisdir,
    aread_text,
    awrite_text,
    astat_size,
    aiterdir,
    amkdir,
    logger,
    file_read_handler,
    file_write_handler,
    file_write_batch_handler,
    file_search_handler,
    _walk_sync,
    file_patch_handler,
    file_edit_handler,
    file_glob_handler,
    mkdir_handler,
)

from app.services.tools.code_execute import (
    logging,
    os,
    subprocess,
    tempfile,
    Path,
    Any,
    CODE_EXECUTE_INSTALL_TIMEOUT,
    CODE_EXECUTE_TIMEOUT,
    MAX_CODE_OUTPUT_CHARS,
    sandbox_executor,
    logger,
    code_execute_handler,
    _is_install_command,
    _is_one_liner,
    _build_python_cmd,
    _run_subprocess,
)

from app.services.tools.memory import (
    logging,
    json,
    os,
    Path,
    Any,
    MEMORY_DIR,
    logger,
    memory_save_handler,
    memory_search_handler,
)

__all__ = [
    "logging",
    "os",
    "subprocess",
    "tempfile",
    "Path",
    "Any",
    "MEMORY_DIR",
    "sandbox_executor",
    "aexists",
    "aisfile",
    "aisdir",
    "aread_text",
    "awrite_text",
    "astat_size",
    "aiterdir",
    "amkdir",
    "logger",
    "MAX_FILE_READ_BYTES",
    "MAX_FILE_LINES",
    "CODE_EXECUTE_TIMEOUT",
    "CODE_EXECUTE_INSTALL_TIMEOUT",
    "MAX_CODE_OUTPUT_CHARS",
    "_safe_path",
    "_compute_unified_diff",
    "_broadcast_workspace_change",
    "_record_file_version",
    "_auto_git_commit",
    "_get_sid_fast",
    "_get_uid_fast",
    "logging",
    "Any",
    "logger",
    "_VALID_SEARCH_MODES",
    "_FREE_PROVIDERS",
    "_resolve_search_providers",
    "_apply_domain_filters",
    "web_search_handler",
    "_make_unavailable_output",
    "_make_search_output",
    "_search_bing",
    "_search_tavily",
    "_search_brave",
    "_search_serpapi",
    "_search_google_cse",
    "_search_duckduckgo",
    "normalize_hit",
    "logging",
    "os",
    "Path",
    "Any",
    "MAX_FILE_READ_BYTES",
    "_auto_git_commit",
    "_broadcast_workspace_change",
    "_compute_unified_diff",
    "_get_sid_fast",
    "_get_uid_fast",
    "aexists",
    "aisfile",
    "aisdir",
    "aread_text",
    "awrite_text",
    "astat_size",
    "aiterdir",
    "amkdir",
    "logger",
    "file_read_handler",
    "file_write_handler",
    "file_write_batch_handler",
    "file_search_handler",
    "_walk_sync",
    "file_patch_handler",
    "file_edit_handler",
    "file_glob_handler",
    "mkdir_handler",
    "logging",
    "os",
    "subprocess",
    "tempfile",
    "Path",
    "Any",
    "CODE_EXECUTE_INSTALL_TIMEOUT",
    "CODE_EXECUTE_TIMEOUT",
    "MAX_CODE_OUTPUT_CHARS",
    "sandbox_executor",
    "logger",
    "code_execute_handler",
    "_is_install_command",
    "_is_one_liner",
    "_build_python_cmd",
    "_run_subprocess",
    "logging",
    "json",
    "os",
    "Path",
    "Any",
    "MEMORY_DIR",
    "logger",
    "memory_save_handler",
    "memory_search_handler",
]