'use client';

import { useState, useCallback } from 'react';
import type { WorkspaceTab, WorkspaceOpEvent } from '../../types';

type TabType = WorkspaceTab['type'];

const TAB_DEFS: { key: TabType; label: string; icon: string; desc: string }[] = [
  { key: 'code', label: '代码', icon: '💻', desc: 'Agent 编写和编辑代码' },
  { key: 'document', label: '文档', icon: '📄', desc: '生成文档和报告' },
  { key: 'canvas', label: '画布', icon: '🎨', desc: '可视化图表与架构' },
  { key: 'data', label: '数据', icon: '📊', desc: '数据探索与分析' },
  { key: 'collaboration', label: '协作', icon: '👥', desc: '人机协作操作历史' },
];

// Mock workspace tabs
const MOCK_TABS: WorkspaceTab[] = [
  { id: 'tab-1', type: 'code', label: 'main.py', path: '/workspace/main.py', language: 'python', content: '# Agent generated code\nimport numpy as np\n\ndef process(data):\n    return np.mean(data)\n' },
  { id: 'tab-2', type: 'code', label: 'app.tsx', path: '/workspace/app.tsx', language: 'typescript', content: '// React component\nconst App = () => <div>Hello AgentHub</div>;\nexport default App;\n' },
  { id: 'tab-3', type: 'document', label: 'README.md', path: '/workspace/README.md', content: '# Project README\n\nGenerated by Agent.\n\n## Installation\n\n```bash\npip install -r requirements.txt\n```\n' },
  { id: 'tab-4', type: 'canvas', label: '架构图', content: '' },
  { id: 'tab-5', type: 'data', label: 'output.csv', content: 'name,value,timestamp\nalpha,42,2026-07-01T10:00:00Z\nbeta,87,2026-07-01T11:00:00Z\ngamma,156,2026-07-02T09:30:00Z\n' },
];

// Mock operation timeline
const MOCK_OPS: WorkspaceOpEvent[] = [
  { id: 'op-1', agent_id: 'planner-agent', operation: 'file:create', target: 'main.py', detail: '创建了项目入口文件', timestamp: '2026-07-02T10:00:01Z' },
  { id: 'op-2', agent_id: 'coder-agent', operation: 'file:write', target: 'main.py', detail: '实现了数据处理函数', timestamp: '2026-07-02T10:02:15Z' },
  { id: 'op-3', agent_id: 'human:user', operation: 'file:edit', target: 'main.py', detail: '修改了 numpy 导入方式', timestamp: '2026-07-02T10:05:30Z' },
  { id: 'op-4', agent_id: 'coder-agent', operation: 'file:write', target: 'app.tsx', detail: '创建了 React 组件', timestamp: '2026-07-02T10:08:00Z' },
  { id: 'op-5', agent_id: 'reviewer-agent', operation: 'file:review', target: 'main.py', detail: '代码审查通过 ✅', timestamp: '2026-07-02T10:12:00Z' },
  { id: 'op-6', agent_id: 'coder-agent', operation: 'command:run', target: 'pip install numpy', detail: '安装依赖成功 (exit=0)', timestamp: '2026-07-02T10:15:00Z' },
  { id: 'op-7', agent_id: 'summarizer-agent', operation: 'doc:generate', target: 'README.md', detail: '生成了项目文档', timestamp: '2026-07-02T10:20:00Z' },
];

const OP_ICONS: Record<string, string> = {
  'file:create': '📄',
  'file:write': '✏️',
  'file:edit': '🔧',
  'file:review': '🔍',
  'command:run': '⚡',
  'doc:generate': '📝',
};

const AGENT_COLORS: Record<string, string> = {
  'planner-agent': '#8b5cf6',
  'coder-agent': '#3b82f6',
  'reviewer-agent': '#22c55e',
  'summarizer-agent': '#f59e0b',
  'human:user': '#ef4444',
};

export default function AgentWorkspace({
  authHeaders: _authHeaders,
  setNotice: _setNotice,
}: {
  authHeaders: () => Record<string, string>;
  setNotice: (msg: string) => void;
}): JSX.Element {
  const [activeTab, setActiveTab] = useState<TabType>('code');
  const [selectedFile, setSelectedFile] = useState<WorkspaceTab | null>(MOCK_TABS[0]);
  const [editContent, setEditContent] = useState('');
  const [isEditing, setIsEditing] = useState(false);
  const [showTimeline, setShowTimeline] = useState(true);

  const handleSelectFile = useCallback((tab: WorkspaceTab) => {
    setSelectedFile(tab);
    setEditContent(tab.content || '');
    setIsEditing(false);
  }, []);

  const handleSaveEdit = () => {
    // MVP: save to local state (production would POST to workspace API)
    if (selectedFile) {
      selectedFile.content = editContent;
      selectedFile.isDirty = true;
    }
    setIsEditing(false);
    _setNotice(`已保存 ${selectedFile?.label}`);
  };

  return (
    <div className="space-y-4">
      {/* Header */}
      <div>
        <h3 className="text-h4">🎯 Agent 多模态工作区</h3>
        <p className="text-xs text-gray-400 mt-1">代码 · 文档 · 画布 · 数据 · 协作 — Agent 与人类共同工作的统一界面</p>
      </div>

      {/* Tab bar */}
      <div className="flex flex-wrap gap-1 border-b border-gray-200 pb-2">
        {TAB_DEFS.map((tab) => (
          <button
            key={tab.key}
            onClick={() => setActiveTab(tab.key)}
            className={`inline-flex items-center gap-2 rounded-t-lg px-4 py-2 text-sm font-medium transition-colors border-b-2 -mb-[9px] ${
              activeTab === tab.key
                ? 'border-primary-500 text-primary-700 bg-primary-50/50'
                : 'border-transparent text-gray-400 hover:text-gray-600'
            }`}
          >
            <span>{tab.icon}</span>
            {tab.label}
          </button>
        ))}
      </div>

      {/* ── Code Tab ─────────────────────────────────────────────── */}
      {activeTab === 'code' && (
        <div className="grid grid-cols-[220px_1fr] gap-4" style={{ minHeight: '400px' }}>
          {/* File tree */}
          <div className="card p-3 space-y-1">
            <h4 className="text-xs font-semibold text-gray-500 mb-2 uppercase tracking-wide">📁 工作区文件</h4>
            {MOCK_TABS.filter((t) => t.type === 'code').map((tab) => (
              <button
                key={tab.id}
                onClick={() => handleSelectFile(tab)}
                className={`w-full text-left text-xs px-2 py-1.5 rounded flex items-center gap-2 transition-colors ${
                  selectedFile?.id === tab.id
                    ? 'bg-primary-50 text-primary-700 font-medium'
                    : 'text-gray-600 hover:bg-gray-50'
                }`}
              >
                <span className="text-xs">{tab.language === 'python' ? '🐍' : tab.language === 'typescript' ? '📘' : '📄'}</span>
                <span className="truncate font-mono">{tab.label}</span>
                {tab.isDirty && <span className="text-amber-500 text-[10px]">●</span>}
              </button>
            ))}

            <div className="pt-3 mt-3 border-t border-gray-100">
              <h5 className="text-[10px] font-semibold text-gray-400 mb-1 uppercase">快捷操作</h5>
              <button
                onClick={() => {
                  _setNotice('Agent 已收到指令，开始编写代码...');
                }}
                className="w-full text-left text-xs px-2 py-1.5 rounded text-gray-500 hover:bg-gray-50"
              >
                🤖 让 Agent 生成代码
              </button>
              <button
                onClick={() => handleSelectFile(MOCK_TABS[0])}
                className="w-full text-left text-xs px-2 py-1.5 rounded text-gray-500 hover:bg-gray-50"
              >
                📥 查看当前文件
              </button>
            </div>
          </div>

          {/* Code editor area */}
          <div className="card overflow-hidden flex flex-col">
            {selectedFile ? (
              <>
                <div className="flex items-center justify-between px-4 py-2 bg-gray-50 border-b border-gray-100">
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-mono text-gray-600">{selectedFile.path}</span>
                    <span className="text-[10px] px-1.5 py-0.5 rounded bg-gray-200 text-gray-500 uppercase">{selectedFile.language}</span>
                    {selectedFile.isDirty && <span className="text-[10px] text-amber-500">已修改</span>}
                  </div>
                  <div className="flex items-center gap-2">
                    {!isEditing ? (
                      <button onClick={() => setIsEditing(true)} className="btn-ghost text-xs">
                        ✏️ 人工接管编辑
                      </button>
                    ) : (
                      <>
                        <button onClick={handleSaveEdit} className="btn-primary text-xs">💾 保存</button>
                        <button onClick={() => { setIsEditing(false); setEditContent(selectedFile.content || ''); }} className="btn-ghost text-xs">取消</button>
                      </>
                    )}
                  </div>
                </div>
                <div className="flex-1 p-4 font-mono text-sm">
                  {isEditing ? (
                    <textarea
                      value={editContent}
                      onChange={(e) => setEditContent(e.target.value)}
                      className="w-full h-full min-h-[300px] p-3 border rounded bg-gray-900 text-green-400 font-mono text-sm resize-none focus:outline-none focus:ring-2 focus:ring-primary-300"
                      spellCheck={false}
                    />
                  ) : (
                    <pre className="text-gray-700 whitespace-pre-wrap bg-gray-50 p-4 rounded min-h-[300px] overflow-auto">
                      <code>{selectedFile.content || '(空文件)'}</code>
                    </pre>
                  )}
                </div>
              </>
            ) : (
              <div className="flex-1 flex items-center justify-center text-gray-400">
                <div className="text-center">
                  <p className="text-4xl mb-3">💻</p>
                  <p>从左侧选择文件查看或编辑</p>
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* ── Document Tab ──────────────────────────────────────────── */}
      {activeTab === 'document' && (
        <div className="grid gap-4">
          {MOCK_TABS.filter((t) => t.type === 'document' || t.type === 'data').map((tab) => (
            <div key={tab.id} className="card p-4">
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2">
                  <span className="text-lg">{tab.type === 'document' ? '📄' : '📊'}</span>
                  <h4 className="font-semibold text-gray-800 font-mono text-sm">{tab.label}</h4>
                  <span className="text-[10px] px-1.5 py-0.5 rounded bg-gray-100 text-gray-500">{tab.type}</span>
                </div>
                <div className="flex gap-2">
                  <button className="btn-ghost text-xs" onClick={() => handleSelectFile(tab)}>
                    👁️ 预览
                  </button>
                  <button className="btn-ghost text-xs" onClick={() => _setNotice('Agent 已收到文档更新指令')}>
                    🤖 Agent 编辑
                  </button>
                </div>
              </div>
              <pre className="text-sm text-gray-600 bg-gray-50 rounded p-3 overflow-auto max-h-48 whitespace-pre-wrap font-mono">
                {tab.content || '(空文档)'}
              </pre>
            </div>
          ))}

          <div className="card p-4 border-2 border-dashed border-gray-200 flex items-center justify-center py-8">
            <button className="text-gray-400 hover:text-gray-600 transition-colors" onClick={() => _setNotice('Agent 开始生成新文档...')}>
              <span className="text-3xl block mb-2">📝</span>
              <span className="text-sm">+ Agent 生成新文档</span>
            </button>
          </div>
        </div>
      )}

      {/* ── Canvas Tab ────────────────────────────────────────────── */}
      {activeTab === 'canvas' && (
        <div className="card p-6" style={{ minHeight: '400px' }}>
          <div className="flex items-center justify-between mb-4">
            <h4 className="font-semibold text-gray-700">🎨 可视化画布</h4>
            <div className="flex gap-2">
              <button className="btn-ghost text-xs">📊 架构图</button>
              <button className="btn-ghost text-xs">🔄 流程图</button>
              <button className="btn-ghost text-xs">📈 时序图</button>
              <button className="btn-primary text-xs" onClick={() => _setNotice('Agent 正在生成可视化图表...')}>🤖 自动生成</button>
            </div>
          </div>
          <div className="bg-gray-50 rounded-lg flex items-center justify-center" style={{ minHeight: '350px' }}>
            <div className="text-center">
              {/* Simple text-based architecture diagram */}
              <pre className="text-xs text-gray-500 font-mono leading-relaxed mb-4">
{`┌─────────────────────────────────────┐
│           🏗️ AgentHub Platform       │
├──────────┬──────────┬────────────────┤
│ Gateway  │ ReAct    │ AgentNet       │
│  :8081   │ Orch.    │  (P2P Mesh)    │
├──────────┼──────────┼────────────────┤
│ Session  │ Tool-Perm│ Audit          │
├──────────┴──────────┴────────────────┤
│   📦 Docker Sandbox (J2)             │
│   🪪 Agent Identity (J1)             │
│   📄 Multimodal Workspace (J3)       │
└─────────────────────────────────────┘`}
              </pre>
              <p className="text-xs text-gray-400">Agent 可自动生成架构图、流程图和时序图</p>
            </div>
          </div>
        </div>
      )}

      {/* ── Data Tab ──────────────────────────────────────────────── */}
      {activeTab === 'data' && (
        <div className="card p-4">
          <h4 className="font-semibold text-gray-700 mb-4">📊 数据探索</h4>
          <div className="overflow-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-200">
                  <th className="text-left py-2 px-3 text-xs font-semibold text-gray-500">name</th>
                  <th className="text-right py-2 px-3 text-xs font-semibold text-gray-500">value</th>
                  <th className="text-left py-2 px-3 text-xs font-semibold text-gray-500">timestamp</th>
                </tr>
              </thead>
              <tbody>
                {['alpha', 'beta', 'gamma'].map((name, i) => (
                  <tr key={name} className="border-b border-gray-50 hover:bg-gray-50">
                    <td className="py-2 px-3 font-mono text-gray-700">{name}</td>
                    <td className="py-2 px-3 text-right font-mono text-gray-700">{[42, 87, 156][i]}</td>
                    <td className="py-2 px-3 text-xs text-gray-400">
                      {new Date(`2026-07-0${i + 1}T${10 + i}:00:00Z`).toLocaleString()}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="flex gap-2 mt-4 pt-4 border-t border-gray-100">
            <button className="btn-ghost text-xs" onClick={() => _setNotice('Agent 开始分析数据...')}>📈 可视化</button>
            <button className="btn-ghost text-xs" onClick={() => _setNotice('Agent 正在执行统计分析...')}>📊 统计分析</button>
            <button className="btn-ghost text-xs">📥 导出 CSV</button>
          </div>
        </div>
      )}

      {/* ── Collaboration Tab ─────────────────────────────────────── */}
      {activeTab === 'collaboration' && (
        <div className="grid grid-cols-1 gap-4">
          {/* Timeline toggle */}
          <div className="flex items-center justify-between">
            <h4 className="font-semibold text-gray-700">👥 操作时间线</h4>
            <label className="flex items-center gap-2 text-xs text-gray-500 cursor-pointer">
              <input
                type="checkbox"
                checked={showTimeline}
                onChange={(e) => setShowTimeline(e.target.checked)}
                className="rounded"
              />
              显示时间线
            </label>
          </div>

          {/* Lock/unlock notice */}
          <div className="card p-4 bg-amber-50/50 border border-amber-200 flex items-center gap-3">
            <span className="text-2xl">🔒</span>
            <div>
              <p className="text-sm font-medium text-amber-700">Agent 锁定模式</p>
              <p className="text-xs text-amber-600">
                当前文件由 Agent 持有锁。点击"人工接管"可解锁并修改，Agent 将等待并接受变更。
              </p>
            </div>
            <button className="btn-primary text-xs shrink-0 ml-auto" onClick={() => _setNotice('Agent 锁已释放，您现在可以编辑文件')}>
              🔓 人工接管
            </button>
          </div>

          {/* Operation timeline */}
          {showTimeline && (
            <div className="card p-4">
              <div className="space-y-0">
                {MOCK_OPS.map((op, i) => (
                  <div key={op.id} className="flex gap-3 pb-3 relative">
                    {/* Timeline line */}
                    {i < MOCK_OPS.length - 1 && (
                      <div className="absolute left-[11px] top-8 bottom-0 w-px bg-gray-200" />
                    )}
                    {/* Dot */}
                    <div
                      className="w-6 h-6 rounded-full flex items-center justify-center shrink-0 mt-0.5 text-xs"
                      style={{ backgroundColor: (AGENT_COLORS[op.agent_id] || '#9ca3af') + '20', color: AGENT_COLORS[op.agent_id] }}
                    >
                      {OP_ICONS[op.operation] || '📌'}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span
                          className="text-xs font-medium px-1.5 py-0.5 rounded"
                          style={{ backgroundColor: (AGENT_COLORS[op.agent_id] || '#9ca3af') + '20', color: AGENT_COLORS[op.agent_id] }}
                        >
                          {op.agent_id}
                        </span>
                        <span className="text-xs text-gray-500">{op.operation}</span>
                        <span className="text-xs font-mono text-gray-400">{op.target}</span>
                      </div>
                      <p className="text-xs text-gray-600 mt-0.5">{op.detail}</p>
                      <p className="text-[10px] text-gray-300 mt-0.5">{new Date(op.timestamp).toLocaleTimeString()}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
